/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package canteen_management_system.ui;

import canteen_management_system.controller.CategoryController;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddCategoryForm extends javax.swing.JPanel {
    CategoryController categoryController = new CategoryController();
    /**
     * Creates new form addCategoryForm
     */
    public AddCategoryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        categoryInput = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionInput = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        addcategoryButton = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(22, 66, 91));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Add Category");

        jPanel1.setBackground(new java.awt.Color(22, 66, 91));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(22, 66, 91));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category Name");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        categoryInput.setBackground(new java.awt.Color(201, 214, 222));
        categoryInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        categoryInput.setForeground(new java.awt.Color(0, 0, 0));
        categoryInput.setPreferredSize(new java.awt.Dimension(71, 30));
        categoryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryInputActionPerformed(evt);
            }
        });
        jPanel2.add(categoryInput, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(22, 66, 91));
        jPanel4.setPreferredSize(new java.awt.Dimension(460, 200));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");
        jPanel4.add(jLabel3, java.awt.BorderLayout.CENTER);

        descriptionInput.setBackground(new java.awt.Color(201, 214, 222));
        descriptionInput.setColumns(20);
        descriptionInput.setRows(5);
        descriptionInput.setPreferredSize(new java.awt.Dimension(232, 60));
        jScrollPane1.setViewportView(descriptionInput);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(22, 66, 91));
        jPanel6.setPreferredSize(new java.awt.Dimension(336, 70));

        addcategoryButton.setBackground(new java.awt.Color(51, 124, 165));
        addcategoryButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        addcategoryButton.setForeground(new java.awt.Color(255, 255, 255));
        addcategoryButton.setText("Add");
        addcategoryButton.setPreferredSize(new java.awt.Dimension(75, 30));
        addcategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(addcategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(addcategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryInputActionPerformed

    private void addcategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcategoryButtonActionPerformed
        String catName = this.categoryInput.getText();
        String description = this.descriptionInput.getText();

        if (catName == null || catName.isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Category name cannot be empty",
                    "Input Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
//        this.categoryController.
      
    }//GEN-LAST:event_addcategoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcategoryButton;
    private javax.swing.JTextField categoryInput;
    private javax.swing.JTextArea descriptionInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
