/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package canteen_management_system.ui;

import canteen_management_system.controller.CustomerController;
import canteen_management_system.model.CustomerModel;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class CustomerForm extends javax.swing.JPanel {

    public CustomerController customerController = new CustomerController();
    public boolean isUpdate = false;
    public CustomerModel toBeUpdated = null;
    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();

    }

    public CustomerForm(int id) {
        initComponents();
        isUpdate = true;
        headerName.setText("Update Customer");
        addCustomerButton.setText("Update");

        this.toBeUpdated = CustomerController.findById(id);
        nameInput.setText(toBeUpdated.getFullName());
        phoneInput.setText(toBeUpdated.getContactNumber());
        balanceInput.setText(String.valueOf(toBeUpdated.getBalance()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerName = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        balanceInput = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        addCustomerButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(22, 66, 91));

        headerName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        headerName.setForeground(new java.awt.Color(255, 255, 255));
        headerName.setText("Add Customer");

        jPanel5.setBackground(new java.awt.Color(22, 66, 91));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(22, 66, 91));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        nameInput.setBackground(new java.awt.Color(201, 214, 222));
        nameInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameInput.setPreferredSize(new java.awt.Dimension(71, 30));
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        jPanel2.add(nameInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(22, 66, 91));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");
        jLabel4.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel3.add(jLabel4, java.awt.BorderLayout.CENTER);

        phoneInput.setBackground(new java.awt.Color(201, 214, 222));
        phoneInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        phoneInput.setPreferredSize(new java.awt.Dimension(71, 30));
        phoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneInputActionPerformed(evt);
            }
        });
        jPanel3.add(phoneInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel3);

        jPanel7.setBackground(new java.awt.Color(22, 66, 91));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Balance");
        jLabel5.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel7.add(jLabel5, java.awt.BorderLayout.CENTER);

        balanceInput.setBackground(new java.awt.Color(201, 214, 222));
        balanceInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        balanceInput.setPreferredSize(new java.awt.Dimension(71, 30));
        balanceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceInputActionPerformed(evt);
            }
        });
        jPanel7.add(balanceInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(22, 66, 91));
        jPanel6.setPreferredSize(new java.awt.Dimension(336, 70));

        addCustomerButton.setBackground(new java.awt.Color(51, 124, 165));
        addCustomerButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerButton.setText("Add");
        addCustomerButton.setPreferredSize(new java.awt.Dimension(75, 30));
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(addCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel5.add(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerName)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(headerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void phoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneInputActionPerformed

    private void balanceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceInputActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        String name = nameInput.getText().trim();
        String phone = phoneInput.getText().trim();
        String balanceStr = balanceInput.getText().trim();
        double balance = 0;

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required!");
            return;
        }

        try {
            balance = Double.parseDouble(balanceStr);
            if (balance < 0) {
                JOptionPane.showMessageDialog(this, "Balance cannot be negative!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid balance!");
            return;
        }

        if (isUpdate) {
            toBeUpdated.setFullName(name);
            toBeUpdated.setContactNumber(phone);
            toBeUpdated.setBalance(balance);
            customerController.updateCustomer(toBeUpdated);
        } else {
            customerController.addCustomer(name, balance);
        }

        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_addCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField balanceInput;
    private javax.swing.JLabel headerName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField phoneInput;
    // End of variables declaration//GEN-END:variables
}
