/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package canteen_management_system.view;

import canteen_management_system.controller.UserController;
import canteen_management_system.enums.Role;
import canteen_management_system.model.UserModel;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class userPanel extends javax.swing.JPanel {

    UserController userController = new UserController();
    UserModel toBeUpdate = null;
    boolean isUpdate = false;

    /**
     * Creates new form userPanel
     */
    public userPanel() {
        initComponents();
        this.setRoleList();
    }

    public userPanel(int id) {
        initComponents();
        this.setRoleList();
        this.toBeUpdate = this.userController.findById(id);
        this.isUpdate = true;
        this.headerName.setText("Update User");
        this.addUserButton.setText("Update");
        this.fullNameInput.setText(toBeUpdate.getFullName());
        this.emailInput.setText(toBeUpdate.getEmail());
        this.phoneNumberInput.setText(toBeUpdate.getPhoneNumber());
        this.roleSelect.setSelectedItem(toBeUpdate.getRole());
        this.passwordInput.setText(toBeUpdate.getPassword());
    }

    private void setRoleList() {
        String[] rl = {Role.ADMIN.toString(), Role.SALES_PERSON.toString()};
        roleSelect.setModel(new javax.swing.DefaultComboBoxModel<>(rl));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerName = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fullNameInput = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        roleSelect = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        phoneNumberInput = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        addUserButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(22, 66, 91));

        headerName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        headerName.setForeground(new java.awt.Color(255, 255, 255));
        headerName.setText("Add User");

        jPanel5.setBackground(new java.awt.Color(22, 66, 91));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(22, 66, 91));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        fullNameInput.setBackground(new java.awt.Color(201, 214, 222));
        fullNameInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fullNameInput.setPreferredSize(new java.awt.Dimension(71, 30));
        fullNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameInputActionPerformed(evt);
            }
        });
        jPanel2.add(fullNameInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel2);

        jPanel8.setBackground(new java.awt.Color(22, 66, 91));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Role");
        jPanel8.add(jLabel6, java.awt.BorderLayout.CENTER);

        roleSelect.setBackground(new java.awt.Color(201, 214, 222));
        roleSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleSelect.setPreferredSize(new java.awt.Dimension(72, 30));
        jPanel8.add(roleSelect, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel8);

        jPanel3.setBackground(new java.awt.Color(22, 66, 91));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, java.awt.BorderLayout.CENTER);

        emailInput.setBackground(new java.awt.Color(201, 214, 222));
        emailInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        emailInput.setPreferredSize(new java.awt.Dimension(71, 30));
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        jPanel3.add(emailInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(22, 66, 91));
        jPanel4.setPreferredSize(new java.awt.Dimension(460, 70));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number");
        jPanel4.add(jLabel3, java.awt.BorderLayout.CENTER);

        phoneNumberInput.setBackground(new java.awt.Color(201, 214, 222));
        phoneNumberInput.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        phoneNumberInput.setPreferredSize(new java.awt.Dimension(71, 30));
        phoneNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberInputActionPerformed(evt);
            }
        });
        jPanel4.add(phoneNumberInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(22, 66, 91));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel7.add(jLabel5, java.awt.BorderLayout.CENTER);

        passwordInput.setBackground(new java.awt.Color(201, 214, 222));
        passwordInput.setForeground(new java.awt.Color(0, 0, 0));
        passwordInput.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel7.add(passwordInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(22, 66, 91));
        jPanel6.setPreferredSize(new java.awt.Dimension(336, 70));

        addUserButton.setBackground(new java.awt.Color(51, 124, 165));
        addUserButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(255, 255, 255));
        addUserButton.setText("Add");
        addUserButton.setPreferredSize(new java.awt.Dimension(75, 30));
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel5.add(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerName)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(headerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        String fullName = fullNameInput.getText().trim();
        String email = emailInput.getText().trim();
        String password = new String(this.passwordInput.getPassword()).trim();
        String phone = phoneNumberInput.getText().trim();
        String role = roleSelect.getSelectedItem().toString();

        String message = null;
        boolean hasError = false;

        // Check required fields
        if (fullName.isEmpty() || email.isEmpty() || password.isEmpty() || phone.isEmpty() || role == null) {
            message = "Please fill in all required fields!";
            hasError = true;
        } // Email format validation
        else if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            message = "Invalid email format!";
            hasError = true;
        } // Phone number validation (digits only, min 7 digits)
        else if (!phone.matches("\\d{7,15}")) {
            message = "Phone number must contain 7-15 digits!";
            hasError = true;
        } // Password length validation (optional)
        else if (password.length() < 6) {
            message = "Password must be at least 6 characters!";
            hasError = true;
        } else if (userController.isEmailExists(email, isUpdate ? toBeUpdate.getId() : null)) {
            message = "User with this email already exists!";
            hasError = true;
        }

        if (hasError) {
            JOptionPane.showMessageDialog(this, message, "Input Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String successMessage = "User added successfully!";
        if (this.isUpdate) {
            toBeUpdate.setFullName(fullName);
            toBeUpdate.setEmail(email);
            toBeUpdate.setPassword(password);
            toBeUpdate.setPhoneNumber(phone);
            toBeUpdate.setRole(role);
            userController.updateUser(toBeUpdate);
            successMessage = "User updated successfully!";
        } else {
            userController.addUser(fullName, email, password, phone, role);
        }

        JOptionPane.showMessageDialog(this,
                successMessage, "Success",
                JOptionPane.INFORMATION_MESSAGE);

        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void phoneNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField fullNameInput;
    private javax.swing.JLabel headerName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField phoneNumberInput;
    private javax.swing.JComboBox<String> roleSelect;
    // End of variables declaration//GEN-END:variables
}
